[server]
host = "0.0.0.0"
port = 3000

[isaaclab]
path = "/home/ywkj"
python_executable = "python"
conda_path = "/home/ywkj/miniconda3" # Placeholder, please verify this path
default_conda_env = "isaaclab"

[storage]
output_path = "/home/ywkj/outputs"
log_path = "/home/ywkj/logs"
database_url = "sqlite:./isaaclab_manager.db"

[tensorboard]
base_port = 6006
max_instances = 10

[sync]
target_path = "/home/ywkj"
default_excludes = [
    "__pycache__",
    "*.pyc",
    ".git",
    "logs/",
    "outputs/",
    ".vscode/",
    "*.tmp",
    "target/",
]

[tasks]
max_concurrent = 1
default_headless = true
timeout_seconds = 86400
working_directory = "/home/ywkj"
